[[plugins]]
  package = "netlify-plugin-a11y"

  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]

  # required config
  checkPaths = ['/', '/articles'] # you can give an array of directories or paths to html files, that you want to run a11y checks on


[[plugins]]
  package = "netlify-plugin-html-validate"

  [plugins.inputs]
  path = './_site/*.html'